language: node_js
node_js: stable

# Travis-CI Caching
cache:
  apt: true
  directories:
    - node_modules


before_script:
  - npm install hexo-cli -g

# S: Build Lifecycle
install:
  - npm install


script:
  - hexo clean
  - hexo g

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "DragonFive"
  - git config user.email "1690302963@qq.com"
  - git add .
  - git commit -m "Update docs 2"
  - git push --force --quiet "https://${blog_ci}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - myblog

env:
 global:
   - GH_REF: github.com/DragonFive/DragonFive.github.io.git
